# Generated by Django 6.1.1 on 2026-09-25 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('CUSTOMER_UNAVAILABLE', 'Customer Unavailable'), ('DAMAGED_GOODS', 'Damaged Goods'), ('INCORRECT_ADDRESS', 'Incorrect Address'), ('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('OTHER', 'Other')], max_length=30)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_stop', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='routes.routestop')),
            ],
        ),
    ]
